#pragma once

#include "ast/token.h"
#include "attributes.h"
#include "intdefs.h"
#include "memory/cstr.h"

/// Keyword lookup struct, points to
/// a keyword in a gnu gperf generated perfect hash table.
struct Keyword {
  /// Id offset into stringpool
  /// To get string for this Keyword add this field to [stringpool]
  i32 id;
  /// TokenType of Keyword. Will always fall in the range
  /// of [Token__KeywordsStart] ... [Token__KeywordsEnd]
  TokenType type;
};

typedef struct Keyword Keyword;
/// Gets a pointer to a static const [Keyword] struct
/// that you can use to get the string value and tokentype of a particular
/// keyword
///
/// The implementation of this funciton is generated by gperf using a script in the
/// build directory. generated file: src/ast/keyword.c
///
/// Returns a nullptr if @param (str) is not equal to any known
/// zeal language reserved keyword
PURE_FUNC
PARAMS_NONNULL(1)
const Keyword* kw_lookup_str(register const char* str, register usize len);

/// Same as [kw_lookup_str], but takes a single [sslice]
/// for an argument
PURE_FUNC
const Keyword* kw_lookup(sslice str);

/// Returns true of @param (str) is exactly equal
/// to a reserved zeal language keyword. otherwise false.
/// Note that @param (len) must exactly match keyword length as well
PURE_FUNC
PARAMS_NONNULL(1)
bool is_keyword(const char* str, usize len);

/// Returns a null-terminated string to the keyword associated
/// with this [Keyword], as that struct contains a id offset into
/// a static const stringpool table, so you cant get to that data
/// from inspecting the [Keyword] value alone
METHOD
PURE_FUNC
const char* kw_string(const Keyword* self);

/// Same as [kw_string] but returns an [sslice] instead of
/// a raw pointer
///
/// Note that the pointer inside the returned [sslice]
/// is to a null-terminated string
///
METHOD
PURE_FUNC
sslice kw_sslice(const Keyword* self);

/// A static global string pool, storing unique strings used
/// in our frontend and backend. Strings live for the entirety
/// of interpreter / compiler runtime
typedef struct StringPool StringPool;

// struct ZString {

// };
// alias(ZString);

typedef enum ZStringType {
  ZString__Rune,
  ZString__Ident,
  ZString__Literal,
  ZString__Keyword,
} ZStringType;

/// An internned String. Could be a Rune, Identifier, or String literal
/// Used for Storing strings used for AST Interpretation and compiler codegen.
typedef struct ZString ZString;
struct ZString {

  u64 hash;
  ZStringType type;
  i32 len;

   char string[];
};

PURE_FUNC
StringPool* stringpool(void);
