#pragma once

#include <stdint.h>
#include <string.h>

#include "ast/token.h"
#include "nv/core/attributes.h"
#include "nv/core/intdefs.h"
#include "nv/core/sslice.h"
#include "nv/core_types.h"

typedef enum KeywordType {
  Keyword__None = -1,
  Keyword__True = 0,
  Keyword__False,
  Keyword__Let,
  Keyword__If,
  Keyword__Else,
  Keyword__Mut,
  Keyword__When,
  Keyword__Fn,
  Keyword__Struct,
  Keyword__Trait,
  Keyword__Impl,
  Keyword__And,
  Keyword__Or,
  Keyword__Return,
  Keyword__Self,
  Keyword__Const,
  Keyword__Loop,
  Keyword__For,
  Keyword__While,
  Keyword__Break,
  Keyword__Match,
  Keyword__Continue,
  Keyword__Pub,
  Keyword__Ref,
  Keyword__Error,
  Keyword__Enum,
  Keyword__Type,
  Keyword__Await,
  Keyword__Comptime,
  Keyword__Static,
  Keyword__Mod,
  Keyword__Macro,
  Keyword__Derive,
  Keyword__Dyn,
  Keyword__Default,
  Keyword__Sizeof,

  Keyword__Count = Token__KeywordCount,

} KeywordType;

/// Keyword lookup struct, points to
/// a keyword in a gnu gperf generated perfect hash table.
struct Keyword {
  /// Id offset into stringpool
  /// To get string for this Keyword add this field to [stringpool]
  i32 id;
  KeywordType type;
};

typedef struct Keyword Keyword;
/// Gets a pointer to a static const [Keyword] struct
/// that you can use to get the string value and tokentype of a particular
/// keyword
///
/// The implementation of this funciton is generated by gperf using a script in the
/// build directory. generated file: src/ast/keyword.c
///
/// Returns a nullptr if @param (str) is not equal to any known
/// zeal language reserved keyword
PURE_FUNC
PARAMS_NONNULL(1)
const Keyword* kw_lookup_str(register const char* str, register size_t len);

/// Same as [kw_lookup_str], but takes a single [sslice]
/// for an argument
PURE_FUNC
const Keyword* kw_lookup(sslice str);

/// Returns true of @param (str) is exactly equal
/// to a reserved zeal language keyword. otherwise false.
/// Note that @param (len) must exactly match keyword length as well
PURE_FUNC
PARAMS_NONNULL(1)
bool is_keyword(const char* str, i32 len);

/// Returns a null-terminated string to the keyword associated
/// with this [Keyword], as that struct contains a id offset into
/// a static const stringpool table, so you cant get to that data
/// from inspecting the [Keyword] value alone
METHOD
PURE_FUNC
const char* kw_string(const Keyword* self);

/// Same as [kw_string] but returns an [sslice] instead of
/// a raw pointer
///
/// Note that the pointer inside the returned [sslice]
/// is to a null-terminated string
///
METHOD
PURE_FUNC
sslice kw_sslice(const Keyword* self);

static inline KeywordType tokentype_keyword(TokenType tt) { return tt - (Token__KeywordsStart + 1); }

CONST_FUNC
const char* kw_literal(Keyword kw);

CONST_FUNC
TokenType kw_tokentype(Keyword kw);

struct Rune {
  /// non-negative if this rune is a reserved language keyword
  KeywordType kwtype;
  u64 hash;
  sslice name;
};
typedef struct Rune Rune;

static constexpr const Rune RUNE_NONE = make_zeroed(Rune);

PURE_FUNC
static inline bool rune_is_none(Rune self) { return memcmp(&self, &RUNE_NONE, sizeof(Rune)) == 0; }

PURE_FUNC
static inline bool rune_is_keyword(Rune self) { return self.kwtype != Keyword__None; }

PURE_FUNC
static inline bool rune_is_ident(Rune self) { return !rune_is_keyword(self); }

PURE_FUNC
static inline bool rune_is_ok(Rune self) { return !rune_is_none(self); }

// TODO: I think if i put a id field on Rune, which is either a incrementing counter id or a byte index of sorts (thats
// unique to memory used by RuneTable), i could probably get away with just comparing that ID to identify if Runes are
// equal, as each entry will correspond to a unique ID, at least for non-keyword Runes, since testing Keyword Runes for
// equality is pretty trivial (testing equality of non-keyword Runes is pretty trivial too, as long as there isnt
// hundreds of entries with huge lengths! We have a INT16_MAX length for strings anyhow, so this probably will never be
// a bottlneck)
//
PURE_FUNC
static inline bool rune_eq(Rune left, Rune right) {
  if (rune_is_keyword(left) && rune_is_keyword(right)) {
    return left.kwtype == right.kwtype;
  }
  return left.hash == right.hash && sslice_eq(left.name, right.name);
}

static constexpr const i32 RUNE_MAX_SIZE = INT16_MAX;

void runetab_init(i32 entry_len, i32 name_storage_in_mb);

PURE_FUNC
f32 runetab_load_factor(void);

/// Resizes entry array, returns new length of array. Does nothing if new_entry_len <= current entry count
i32 runetab_grow(i32 new_entry_len);

Rune runetab_add(sslice name);

PURE_FUNC
bool runetab_has(Rune rune);

PURE_FUNC
bool runetab_has_str(const char* string, i32 string_len);

PURE_FUNC
Rune runetab_lookup(sslice name);

void runetab_destroy(void);

void runetab_clear(void);

void runetab_print_entries(void);
